
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jackson:
    time-zone: Europe/Moscow
    locale: ru_RU
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.example.artship: DEBUG
    org.springframework.security: DEBUG
    org.mongodb.driver: INFO

app:
  cookie:
    secure: false  
    domain:  